{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMMLL9JEHWA77HKGQZby5bU"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","source":["!pip install face-recognition"],"metadata":{"collapsed":true,"colab":{"base_uri":"https://localhost:8080/"},"id":"ryLeVxQEcJSu","executionInfo":{"status":"ok","timestamp":1744988870725,"user_tz":-330,"elapsed":29237,"user":{"displayName":"Tejas","userId":"17988002090652757746"}},"outputId":"5b6d6cf4-c8f4-42e6-db00-bcf463a6ef2f"},"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Collecting face-recognition\n","  Downloading face_recognition-1.3.0-py2.py3-none-any.whl.metadata (21 kB)\n","Collecting face-recognition-models>=0.3.0 (from face-recognition)\n","  Downloading face_recognition_models-0.3.0.tar.gz (100.1 MB)\n","\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m100.1/100.1 MB\u001b[0m \u001b[31m8.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n","\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (8.1.8)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (19.24.6)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from face-recognition) (2.0.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from face-recognition) (11.1.0)\n","Downloading face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n","Building wheels for collected packages: face-recognition-models\n","  Building wheel for face-recognition-models (setup.py) ... \u001b[?25l\u001b[?25hdone\n","  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566166 sha256=c7368e7b94e82918c77a85404f3b66b62fa3f47f250796fd3290d1c1664a7340\n","  Stored in directory: /root/.cache/pip/wheels/04/52/ec/9355da79c29f160b038a20c784db2803c2f9fa2c8a462c176a\n","Successfully built face-recognition-models\n","Installing collected packages: face-recognition-models, face-recognition\n","Successfully installed face-recognition-1.3.0 face-recognition-models-0.3.0\n"]}]},{"cell_type":"code","source":["!pip install dlib --no-cuda"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"LvU315f7co5U","executionInfo":{"status":"ok","timestamp":1744988970941,"user_tz":-330,"elapsed":859,"user":{"displayName":"Tejas","userId":"17988002090652757746"}},"outputId":"3753f23b-c569-467e-f2d8-d247da144973"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Usage:   \n","  pip3 install [options] <requirement specifier> [package-index-options] ...\n","  pip3 install [options] -r <requirements file> [package-index-options] ...\n","  pip3 install [options] [-e] <vcs project url> ...\n","  pip3 install [options] [-e] <local project path> ...\n","  pip3 install [options] <archive url/path> ...\n","\n","no such option: --no-cuda\n"]}]},{"cell_type":"code","source":["!pip uninstall face-recognition -y  # Uninstall first\n","!pip install face-recognition --no-cuda"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"UNZ7VxONc0KV","executionInfo":{"status":"ok","timestamp":1744989018773,"user_tz":-330,"elapsed":2239,"user":{"displayName":"Tejas","userId":"17988002090652757746"}},"outputId":"4b4c2860-6183-471d-870e-d0cc5570ce67"},"execution_count":7,"outputs":[{"output_type":"stream","name":"stdout","text":["Found existing installation: face-recognition 1.3.0\n","Uninstalling face-recognition-1.3.0:\n","  Successfully uninstalled face-recognition-1.3.0\n","\n","Usage:   \n","  pip3 install [options] <requirement specifier> [package-index-options] ...\n","  pip3 install [options] -r <requirements file> [package-index-options] ...\n","  pip3 install [options] [-e] <vcs project url> ...\n","  pip3 install [options] [-e] <local project path> ...\n","  pip3 install [options] <archive url/path> ...\n","\n","no such option: --no-cuda\n"]}]},{"cell_type":"code","source":["import os\n","os.environ[\"CUDA_VISIBLE_DEVICES\"] = \"-1\"\n"],"metadata":{"id":"fYKMRlnvhb5O","executionInfo":{"status":"ok","timestamp":1744990227547,"user_tz":-330,"elapsed":5,"user":{"displayName":"Tejas","userId":"17988002090652757746"}}},"execution_count":12,"outputs":[]},{"cell_type":"code","source":["!pip install face-recognition\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"4AKXQ97ni1A-","executionInfo":{"status":"ok","timestamp":1744990598621,"user_tz":-330,"elapsed":3751,"user":{"displayName":"Tejas","userId":"17988002090652757746"}},"outputId":"2e83143c-5b8b-454b-8625-d290cfd73edb"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: face-recognition in /usr/local/lib/python3.11/dist-packages (1.3.0)\n","Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (0.3.0)\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (8.1.8)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (19.24.6)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from face-recognition) (2.0.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from face-recognition) (11.1.0)\n"]}]},{"cell_type":"code","source":["# Patch face_recognition to remove CNN model (which requires GPU)\n","!sed -i '/cnn_face_detector =/,+1d' /usr/local/lib/python3.11/dist-packages/face_recognition/api.py\n"],"metadata":{"id":"I4RzwC7Ai3SQ","executionInfo":{"status":"ok","timestamp":1744990611403,"user_tz":-330,"elapsed":116,"user":{"displayName":"Tejas","userId":"17988002090652757746"}}},"execution_count":16,"outputs":[]},{"cell_type":"code","execution_count":13,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":671},"id":"gi_Ro9qNbLj1","executionInfo":{"status":"error","timestamp":1744990238159,"user_tz":-330,"elapsed":8009,"user":{"displayName":"Tejas","userId":"17988002090652757746"}},"outputId":"95a3e6be-3c41-4c24-bf49-f13c3a8dd981"},"outputs":[{"output_type":"stream","name":"stdout","text":["Requirement already satisfied: face-recognition in /usr/local/lib/python3.11/dist-packages (1.3.0)\n","Requirement already satisfied: face-recognition-models>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (0.3.0)\n","Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (8.1.8)\n","Requirement already satisfied: dlib>=19.7 in /usr/local/lib/python3.11/dist-packages (from face-recognition) (19.24.6)\n","Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from face-recognition) (2.0.2)\n","Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from face-recognition) (11.1.0)\n","Requirement already satisfied: dlib in /usr/local/lib/python3.11/dist-packages (19.24.6)\n"]},{"output_type":"error","ename":"RuntimeError","evalue":"Error while calling cudaGetDevice(&the_device_id) in file /root/.cache/uv/sdists-v9/pypi/dlib/19.24.6/AJxE63M-IFcdC7-5Ufol7/src/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)","\u001b[0;32m<ipython-input-13-f242f72bf375>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip install dlib'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcv2\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 4\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;32m/usr/local/lib/python3.11/dist-packages/face_recognition/__init__.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0m__version__\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'1.2.3'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0;34m.\u001b[0m\u001b[0mapi\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mload_image_file\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbatch_face_locations\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_landmarks\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_encodings\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompare_faces\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mface_distance\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m/usr/local/lib/python3.11/dist-packages/face_recognition/api.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     24\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     25\u001b[0m \u001b[0mcnn_face_detection_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detector_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 26\u001b[0;31m \u001b[0mcnn_face_detector\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcnn_face_detection_model_v1\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcnn_face_detection_model\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     27\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     28\u001b[0m \u001b[0mface_recognition_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mface_recognition_models\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mface_recognition_model_location\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mRuntimeError\u001b[0m: Error while calling cudaGetDevice(&the_device_id) in file /root/.cache/uv/sdists-v9/pypi/dlib/19.24.6/AJxE63M-IFcdC7-5Ufol7/src/dlib/cuda/gpu_data.cpp:204. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version"]}],"source":["!pip install face-recognition --no-binary :all:\n","!pip install dlib\n","import cv2\n","import face_recognition\n","import numpy as np\n","import pandas as pd\n","import os\n","import datetime\n","import tkinter as tk\n","from tkinter import messagebox\n","from PIL import Image, ImageTk\n","\n","# Encode faces from the dataset\n","def encode_faces_from_images():\n","    encoded_faces = {}\n","    for person_name in os.listdir('dataset'):\n","        person_path = os.path.join('dataset', person_name)\n","        if os.path.isdir(person_path):\n","            encodings = []\n","            for image_name in os.listdir(person_path):\n","                image_path = os.path.join(person_path, image_name)\n","                img = face_recognition.load_image_file(image_path)\n","                face_enc = face_recognition.face_encodings(img)\n","                if face_enc:\n","                    encodings.append(face_enc[0])\n","            if encodings:\n","                if person_name == \"person1\":\n","                    person_name = \"Tejas.k\"\n","                elif person_name == \"person2\":\n","                    person_name = \"Sagar.s\"\n","                encoded_faces[person_name] = encodings\n","    return encoded_faces\n","\n","# Load known faces\n","known_encodings = encode_faces_from_images()\n","known_names = list(known_encodings.keys())\n","\n","# Initialize attendance dictionaries\n","attendance = {}\n","attendance_images = {}\n","\n","# Attendance marking function\n","def mark_attendance(name, frame, face_location):\n","    if name not in attendance:\n","        # Capture the time of attendance\n","        timestamp = datetime.datetime.now().strftime('%I:%M:%S %p')  # 12-hour format\n","        attendance[name] = timestamp\n","\n","        # Save the image of the detected face\n","        top, right, bottom, left = face_location\n","        face_image = frame[top:bottom, left:right]\n","        face_image = cv2.cvtColor(face_image, cv2.COLOR_BGR2RGB)  # Convert to RGB for saving\n","\n","        # Generate a unique filename for the image\n","        image_filename = f\"photos/{name}_{datetime.datetime.now().strftime('%Y-%m-%d_%I-%M-%S %p')}.jpg\"\n","        os.makedirs(os.path.dirname(image_filename), exist_ok=True)  # Ensure the directory exists\n","        cv2.imwrite(image_filename, cv2.cvtColor(face_image, cv2.COLOR_RGB2BGR))  # Save as BGR\n","\n","        # Save the absolute path of the image in the attendance record\n","        attendance_images[name] = os.path.abspath(image_filename)\n","\n","        # Inform the user\n","        messagebox.showinfo(\"Attendance Marked\", f\"Attendance marked for {name}\")\n","\n","# GUI setup\n","class AttendanceApp:\n","    def __init__(self, root):\n","        self.root = root\n","        self.root.title(\"AI-Based Attendance System\")\n","        self.root.geometry(\"800x600\")\n","\n","        self.video_capture = None\n","        self.is_running = False\n","\n","        # Create start and stop buttons\n","        self.start_button = tk.Button(root, text=\"Start Attendance\", command=self.start_attendance)\n","        self.start_button.pack(pady=10)\n","\n","        self.stop_button = tk.Button(root, text=\"Stop Attendance\", command=self.stop_attendance)\n","        self.stop_button.pack(pady=10)\n","\n","        # Video display label\n","        self.video_label = tk.Label(root)\n","        self.video_label.pack()\n","\n","    # Start video capture and attendance\n","    def start_attendance(self):\n","        if not self.is_running:\n","            self.video_capture = cv2.VideoCapture(0)\n","            self.is_running = True\n","            self.update_frame()\n","\n","    # Stop video capture and save attendance\n","    def stop_attendance(self):\n","        if self.is_running:\n","            self.is_running = False\n","            self.video_capture.release()\n","            # Save attendance to a CSV file\n","            self.save_attendance()\n","\n","    # Save attendance to a CSV file\n","    def save_attendance(self):\n","        current_date = datetime.datetime.now().strftime('%Y-%m-%d')  # Current date\n","        attendance_data = [\n","            {\n","                \"Name\": name,\n","                \"Date\": current_date,  # Add the date\n","                \"Time\": time,\n","                \"Photo\": f'=HYPERLINK(\"{attendance_images.get(name, \"\")}\", \"View Photo\")'\n","            }\n","            for name, time in attendance.items()\n","        ]\n","        attendance_df = pd.DataFrame(attendance_data)\n","\n","        # Generate a unique filename based on date and time\n","        timestamp = datetime.datetime.now().strftime('%Y-%m-%d_%I-%M-%S %p')\n","        filename = f\"attendance_{timestamp}.csv\"\n","\n","        # Save to CSV\n","        attendance_df.to_csv(filename, index=False)\n","        messagebox.showinfo(\"Attendance Saved\", f\"Attendance saved to {filename}\")\n","\n","    # Update the video frame\n","    def update_frame(self):\n","        if self.is_running:\n","            ret, frame = self.video_capture.read()\n","            if not ret:\n","                self.stop_attendance()\n","                return\n","\n","            # Process the frame\n","            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n","            face_locations = face_recognition.face_locations(rgb_frame)\n","            face_encodings = face_recognition.face_encodings(rgb_frame, face_locations)\n","\n","            for face_encoding, face_location in zip(face_encodings, face_locations):\n","                name = \"Unknown\"\n","                for known_name, encodings in known_encodings.items():\n","                    matches = face_recognition.compare_faces(encodings, face_encoding, tolerance=0.6)\n","                    if any(matches):\n","                        name = known_name\n","                        mark_attendance(name, frame, face_location)\n","                        break\n","\n","                # Draw a box around the face\n","                top, right, bottom, left = face_location\n","                cv2.rectangle(frame, (left, top), (right, bottom), (0, 255, 0), 2)\n","                cv2.putText(frame, name, (left, top - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)\n","\n","            # Convert frame for tkinter\n","            img = Image.fromarray(rgb_frame)\n","            imgtk = ImageTk.PhotoImage(image=img)\n","            self.video_label.imgtk = imgtk\n","            self.video_label.configure(image=imgtk)\n","            self.video_label.after(10, self.update_frame)\n","\n","# Main function\n","if __name__ == \"__main__\":\n","    root = tk.Tk()\n","    app = AttendanceApp(root)\n","    root.mainloop()\n"]},{"cell_type":"code","source":[],"metadata":{"id":"W-mUqhQZcrN6"},"execution_count":null,"outputs":[]}]}